BEGIN;

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-22 16:49:52

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET search_path = public;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 264 (class 1255 OID 16708)
-- Name: generar_numero_factura(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION public.generar_numero_factura() RETURNS character varying(30)
    LANGUAGE plpgsql
    AS $$
DECLARE
    consecutivo BIGINT;
BEGIN
    consecutivo := nextval('factura_numero_seq');
    RETURN 'FAC-' || TO_CHAR(CURRENT_DATE, 'YYYY') || '-' || LPAD(consecutivo::TEXT, 6, '0');
END;
$$;



--
-- TOC entry 263 (class 1255 OID 16389)
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 16417)
-- Name: categorias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias (
    id integer NOT NULL,
    nombre character varying(80) NOT NULL,
    descripcion character varying(255),
    estado character varying(10) DEFAULT 'activo'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT categorias_estado_check CHECK (((estado)::text = ANY ((ARRAY['activo'::character varying, 'inactivo'::character varying])::text[])))
);



--
-- TOC entry 223 (class 1259 OID 16416)
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categorias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 16879)
-- Name: conversaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conversaciones (
    id integer NOT NULL,
    usuario_id integer,
    pqr_id integer,
    canal character varying(20) DEFAULT 'web'::character varying NOT NULL,
    estado character varying(15) DEFAULT 'activa'::character varying NOT NULL,
    titulo character varying(180),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT conversaciones_canal_check CHECK (((canal)::text = ANY ((ARRAY['web'::character varying, 'admin'::character varying, 'otro'::character varying])::text[]))),
    CONSTRAINT conversaciones_estado_check CHECK (((estado)::text = ANY ((ARRAY['activa'::character varying, 'cerrada'::character varying])::text[])))
);



--
-- TOC entry 253 (class 1259 OID 16878)
-- Name: conversaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.conversaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 16759)
-- Name: detalle_facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_facturas (
    id integer NOT NULL,
    factura_id integer NOT NULL,
    producto_id integer,
    servicio_id integer,
    tipo character varying(10) NOT NULL,
    descripcion character varying(255) NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(12,2) NOT NULL,
    descuento numeric(12,2) DEFAULT 0 NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    CONSTRAINT ck_detalle_facturas_item CHECK (((((tipo)::text = 'producto'::text) AND (producto_id IS NOT NULL) AND (servicio_id IS NULL)) OR (((tipo)::text = 'servicio'::text) AND (servicio_id IS NOT NULL) AND (producto_id IS NULL)))),
    CONSTRAINT detalle_facturas_cantidad_check CHECK ((cantidad > 0)),
    CONSTRAINT detalle_facturas_descuento_check CHECK ((descuento >= (0)::numeric)),
    CONSTRAINT detalle_facturas_precio_unitario_check CHECK ((precio_unitario >= (0)::numeric)),
    CONSTRAINT detalle_facturas_subtotal_check CHECK ((subtotal >= (0)::numeric)),
    CONSTRAINT detalle_facturas_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['producto'::character varying, 'servicio'::character varying])::text[])))
);



--
-- TOC entry 245 (class 1259 OID 16758)
-- Name: detalle_facturas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_facturas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_facturas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16677)
-- Name: detalle_pagos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_pagos (
    id integer NOT NULL,
    payment_id integer NOT NULL,
    producto_id integer,
    servicio_id integer,
    tipo character varying(10) DEFAULT 'producto'::character varying NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(12,2) NOT NULL,
    CONSTRAINT ck_detalle_pagos_item_exclusivo CHECK (((((tipo)::text = 'producto'::text) AND (producto_id IS NOT NULL) AND (servicio_id IS NULL)) OR (((tipo)::text = 'servicio'::text) AND (servicio_id IS NOT NULL) AND (producto_id IS NULL)))),
    CONSTRAINT detalle_pagos_cantidad_check CHECK ((cantidad > 0)),
    CONSTRAINT detalle_pagos_precio_unitario_check CHECK ((precio_unitario >= (0)::numeric)),
    CONSTRAINT detalle_pagos_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['producto'::character varying, 'servicio'::character varying])::text[])))
);



--
-- TOC entry 240 (class 1259 OID 16676)
-- Name: detalle_pagos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_pagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16595)
-- Name: detalle_ventas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_ventas (
    id integer NOT NULL,
    venta_id integer NOT NULL,
    producto_id integer,
    servicio_id integer,
    tipo character varying(10) NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(12,2) NOT NULL,
    descuento numeric(12,2) DEFAULT 0 NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_detalle_ventas_item_exclusivo CHECK (((((tipo)::text = 'producto'::text) AND (producto_id IS NOT NULL) AND (servicio_id IS NULL)) OR (((tipo)::text = 'servicio'::text) AND (servicio_id IS NOT NULL) AND (producto_id IS NULL)))),
    CONSTRAINT detalle_ventas_cantidad_check CHECK ((cantidad > 0)),
    CONSTRAINT detalle_ventas_descuento_check CHECK ((descuento >= (0)::numeric)),
    CONSTRAINT detalle_ventas_precio_unitario_check CHECK ((precio_unitario >= (0)::numeric)),
    CONSTRAINT detalle_ventas_subtotal_check CHECK ((subtotal >= (0)::numeric)),
    CONSTRAINT detalle_ventas_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['producto'::character varying, 'servicio'::character varying])::text[])))
);



--
-- TOC entry 236 (class 1259 OID 16594)
-- Name: detalle_ventas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_ventas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_ventas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 16707)
-- Name: factura_numero_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.factura_numero_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- TOC entry 244 (class 1259 OID 16710)
-- Name: facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.facturas (
    id integer NOT NULL,
    venta_id integer NOT NULL,
    cliente_id integer NOT NULL,
    numero_factura character varying(30) DEFAULT public.generar_numero_factura() NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    subtotal numeric(12,2) DEFAULT 0 NOT NULL,
    descuento numeric(12,2) DEFAULT 0 NOT NULL,
    impuestos numeric(12,2) DEFAULT 0 NOT NULL,
    total numeric(12,2) NOT NULL,
    moneda character varying(3) DEFAULT 'COP'::character varying NOT NULL,
    estado character varying(20) DEFAULT 'emitida'::character varying NOT NULL,
    cliente_nombre character varying(120) NOT NULL,
    cliente_documento character varying(30) NOT NULL,
    cliente_email character varying(120),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT facturas_descuento_check CHECK ((descuento >= (0)::numeric)),
    CONSTRAINT facturas_estado_check CHECK (((estado)::text = ANY ((ARRAY['emitida'::character varying, 'pagada'::character varying, 'anulada'::character varying])::text[]))),
    CONSTRAINT facturas_impuestos_check CHECK ((impuestos >= (0)::numeric)),
    CONSTRAINT facturas_subtotal_check CHECK ((subtotal >= (0)::numeric)),
    CONSTRAINT facturas_total_check CHECK ((total >= (0)::numeric))
);



--
-- TOC entry 243 (class 1259 OID 16709)
-- Name: facturas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.facturas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.facturas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 16906)
-- Name: mensajes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mensajes (
    id integer NOT NULL,
    conversacion_id integer NOT NULL,
    remitente character varying(15) NOT NULL,
    usuario_id integer,
    contenido text NOT NULL,
    proveedor_ia character varying(50),
    modelo_ia character varying(100),
    tokens_entrada integer,
    tokens_salida integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT mensajes_remitente_check CHECK (((remitente)::text = ANY ((ARRAY['usuario'::character varying, 'asistente'::character varying, 'sistema'::character varying])::text[]))),
    CONSTRAINT mensajes_tokens_entrada_check CHECK (((tokens_entrada IS NULL) OR (tokens_entrada >= 0))),
    CONSTRAINT mensajes_tokens_salida_check CHECK (((tokens_salida IS NULL) OR (tokens_salida >= 0)))
);



--
-- TOC entry 255 (class 1259 OID 16905)
-- Name: mensajes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mensajes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensajes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16632)
-- Name: pagos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagos (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    venta_id integer,
    producto_id integer,
    cantidad integer,
    proveedor character varying(20) DEFAULT 'stripe'::character varying NOT NULL,
    metodo_pago character varying(30),
    stripe_session_id character varying(255),
    stripe_payment_intent_id character varying(255),
    referencia_externa character varying(255),
    monto numeric(12,2) NOT NULL,
    moneda character varying(3) DEFAULT 'COP'::character varying NOT NULL,
    estado character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    mensaje_error text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_pagos_referencia_comercial CHECK (((venta_id IS NOT NULL) OR (producto_id IS NOT NULL) OR (referencia_externa IS NOT NULL))),
    CONSTRAINT pagos_cantidad_check CHECK (((cantidad IS NULL) OR (cantidad > 0))),
    CONSTRAINT pagos_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT pagos_monto_check CHECK ((monto >= (0)::numeric)),
    CONSTRAINT pagos_proveedor_check CHECK (((proveedor)::text = ANY ((ARRAY['stripe'::character varying, 'manual'::character varying, 'otro'::character varying])::text[])))
);



--
-- TOC entry 238 (class 1259 OID 16631)
-- Name: pagos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16533)
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_tokens (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone
);



--
-- TOC entry 232 (class 1259 OID 16532)
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16405)
-- Name: permisos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permisos (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);



--
-- TOC entry 221 (class 1259 OID 16404)
-- Name: permisos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permisos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permisos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 16819)
-- Name: pqr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pqr (
    id integer NOT NULL,
    cliente_id integer NOT NULL,
    asignado_a integer,
    tipo character varying(20) NOT NULL,
    asunto character varying(180) NOT NULL,
    descripcion text NOT NULL,
    estado character varying(20) DEFAULT 'pendiente'::character varying NOT NULL,
    prioridad character varying(10) DEFAULT 'media'::character varying NOT NULL,
    fecha_cierre timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pqr_estado_check CHECK (((estado)::text = ANY ((ARRAY['pendiente'::character varying, 'en_proceso'::character varying, 'respondida'::character varying, 'cerrada'::character varying])::text[]))),
    CONSTRAINT pqr_prioridad_check CHECK (((prioridad)::text = ANY ((ARRAY['baja'::character varying, 'media'::character varying, 'alta'::character varying])::text[]))),
    CONSTRAINT pqr_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['peticion'::character varying, 'queja'::character varying, 'reclamo'::character varying, 'sugerencia'::character varying, 'otro'::character varying])::text[])))
);



--
-- TOC entry 249 (class 1259 OID 16818)
-- Name: pqr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pqr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pqr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 16853)
-- Name: pqr_respuestas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pqr_respuestas (
    id integer NOT NULL,
    pqr_id integer NOT NULL,
    usuario_id integer NOT NULL,
    mensaje text NOT NULL,
    es_interna boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);



--
-- TOC entry 251 (class 1259 OID 16852)
-- Name: pqr_respuestas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pqr_respuestas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pqr_respuestas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16454)
-- Name: productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos (
    id integer NOT NULL,
    nombre character varying(120) NOT NULL,
    descripcion text,
    precio numeric(12,2) DEFAULT 0.00 NOT NULL,
    stock integer DEFAULT 0 NOT NULL,
    imagen character varying(255),
    categoria_id integer,
    estado character varying(10) DEFAULT 'activo'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT productos_estado_check CHECK (((estado)::text = ANY ((ARRAY['activo'::character varying, 'inactivo'::character varying])::text[]))),
    CONSTRAINT productos_precio_check CHECK ((precio >= (0)::numeric)),
    CONSTRAINT productos_stock_check CHECK ((stock >= 0))
);



--
-- TOC entry 227 (class 1259 OID 16453)
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 16795)
-- Name: reportes_generados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reportes_generados (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    tipo character varying(30) DEFAULT 'ventas_diarias'::character varying NOT NULL,
    formato character varying(10) NOT NULL,
    fecha_inicial date,
    fecha_final date,
    filtros jsonb DEFAULT '{}'::jsonb NOT NULL,
    nombre_archivo character varying(255),
    ruta_archivo character varying(500),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT reportes_generados_formato_check CHECK (((formato)::text = ANY ((ARRAY['PDF'::character varying, 'XLSX'::character varying, 'CSV'::character varying])::text[]))),
    CONSTRAINT reportes_generados_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ventas_diarias'::character varying, 'ventas_periodo'::character varying, 'facturacion'::character varying, 'pqr'::character varying, 'otro'::character varying])::text[])))
);



--
-- TOC entry 247 (class 1259 OID 16794)
-- Name: reportes_generados_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reportes_generados ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reportes_generados_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16515)
-- Name: rol_permisos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol_permisos (
    rol_id integer NOT NULL,
    permiso_id integer NOT NULL
);



--
-- TOC entry 220 (class 1259 OID 16391)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);



--
-- TOC entry 219 (class 1259 OID 16390)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16434)
-- Name: servicios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.servicios (
    id integer NOT NULL,
    nombre character varying(120) NOT NULL,
    descripcion text,
    precio numeric(12,2) DEFAULT 0.00 NOT NULL,
    estado character varying(10) DEFAULT 'activo'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT servicios_estado_check CHECK (((estado)::text = ANY ((ARRAY['activo'::character varying, 'inactivo'::character varying])::text[]))),
    CONSTRAINT servicios_precio_check CHECK ((precio >= (0)::numeric))
);



--
-- TOC entry 225 (class 1259 OID 16433)
-- Name: servicios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.servicios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16482)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    nombre character varying(50) NOT NULL,
    apellido character varying(50) NOT NULL,
    tipo_documento character varying(20) NOT NULL,
    numero_documento character varying(20) NOT NULL,
    direccion character varying(120) NOT NULL,
    telefono character varying(20) NOT NULL,
    email character varying(120) NOT NULL,
    password character varying(255) NOT NULL,
    rol_id integer NOT NULL,
    estado character varying(10) DEFAULT 'activo'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT usuarios_estado_check CHECK (((estado)::text = ANY ((ARRAY['activo'::character varying, 'inactivo'::character varying])::text[])))
);



--
-- TOC entry 229 (class 1259 OID 16481)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16550)
-- Name: ventas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ventas (
    id integer NOT NULL,
    cliente_id integer,
    usuario_id integer,
    subtotal numeric(12,2) DEFAULT 0 NOT NULL,
    descuento numeric(12,2) DEFAULT 0 NOT NULL,
    impuestos numeric(12,2) DEFAULT 0 NOT NULL,
    total numeric(12,2) NOT NULL,
    moneda character varying(3) DEFAULT 'COP'::character varying NOT NULL,
    estado character varying(20) DEFAULT 'pendiente'::character varying NOT NULL,
    origen character varying(20) DEFAULT 'web'::character varying NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    observaciones text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ventas_descuento_check CHECK ((descuento >= (0)::numeric)),
    CONSTRAINT ventas_estado_check CHECK (((estado)::text = ANY ((ARRAY['pendiente'::character varying, 'pagada'::character varying, 'cancelada'::character varying, 'reembolsada'::character varying])::text[]))),
    CONSTRAINT ventas_impuestos_check CHECK ((impuestos >= (0)::numeric)),
    CONSTRAINT ventas_origen_check CHECK (((origen)::text = ANY ((ARRAY['web'::character varying, 'empleado'::character varying, 'admin'::character varying, 'legacy'::character varying])::text[]))),
    CONSTRAINT ventas_subtotal_check CHECK ((subtotal >= (0)::numeric)),
    CONSTRAINT ventas_total_check CHECK ((total >= (0)::numeric))
);



--
-- TOC entry 234 (class 1259 OID 16549)
-- Name: ventas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ventas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 16987)
-- Name: vw_dashboard_admin; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_dashboard_admin AS
 SELECT ( SELECT count(*) AS count
           FROM public.usuarios) AS total_usuarios,
    ( SELECT count(*) AS count
           FROM public.productos
          WHERE ((productos.estado)::text = 'activo'::text)) AS productos_activos,
    ( SELECT count(*) AS count
           FROM public.servicios
          WHERE ((servicios.estado)::text = 'activo'::text)) AS servicios_activos,
    ( SELECT count(*) AS count
           FROM public.ventas) AS total_ventas,
    ( SELECT COALESCE(sum(ventas.total), (0)::numeric) AS "coalesce"
           FROM public.ventas
          WHERE ((ventas.estado)::text = 'pagada'::text)) AS valor_ventas_pagadas,
    ( SELECT count(*) AS count
           FROM public.facturas) AS total_facturas,
    ( SELECT COALESCE(sum(facturas.total), (0)::numeric) AS "coalesce"
           FROM public.facturas
          WHERE ((facturas.estado)::text = ANY ((ARRAY['emitida'::character varying, 'pagada'::character varying])::text[]))) AS total_facturacion,
    ( SELECT count(*) AS count
           FROM public.pqr) AS total_pqr,
    ( SELECT count(*) AS count
           FROM public.pqr
          WHERE ((pqr.estado)::text = ANY ((ARRAY['pendiente'::character varying, 'en_proceso'::character varying])::text[]))) AS pqr_pendientes;



--
-- TOC entry 257 (class 1259 OID 16977)
-- Name: vw_historial_ventas; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_historial_ventas AS
 SELECT v.id AS venta_id,
    v.fecha,
    v.estado,
    v.origen,
    v.subtotal,
    v.descuento,
    v.impuestos,
    v.total,
    v.moneda,
    v.cliente_id,
        CASE
            WHEN (c.id IS NULL) THEN NULL::text
            ELSE concat(c.nombre, ' ', c.apellido)
        END AS cliente_nombre,
    c.numero_documento AS cliente_documento,
    c.email AS cliente_email,
    v.usuario_id,
        CASE
            WHEN (u.id IS NULL) THEN NULL::text
            ELSE concat(u.nombre, ' ', u.apellido)
        END AS usuario_operacion,
    dv.id AS detalle_id,
    dv.tipo,
    dv.producto_id,
    dv.servicio_id,
    COALESCE(p.nombre, s.nombre) AS item_nombre,
    dv.cantidad,
    dv.precio_unitario,
    dv.descuento AS detalle_descuento,
    dv.subtotal AS detalle_subtotal
   FROM (((((public.ventas v
     LEFT JOIN public.usuarios c ON ((c.id = v.cliente_id)))
     LEFT JOIN public.usuarios u ON ((u.id = v.usuario_id)))
     JOIN public.detalle_ventas dv ON ((dv.venta_id = v.id)))
     LEFT JOIN public.productos p ON ((p.id = dv.producto_id)))
     LEFT JOIN public.servicios s ON ((s.id = dv.servicio_id)));



--
-- TOC entry 262 (class 1259 OID 17001)
-- Name: vw_pqr_resumen_estados; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_pqr_resumen_estados AS
 SELECT estado,
    count(*) AS cantidad
   FROM public.pqr
  GROUP BY estado;



--
-- TOC entry 258 (class 1259 OID 16982)
-- Name: vw_reporte_diario_ventas; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_reporte_diario_ventas AS
 SELECT date(v.fecha) AS fecha_reporte,
    v.id AS numero_venta,
    v.estado,
    COALESCE(concat(c.nombre, ' ', c.apellido), 'Cliente no registrado'::text) AS cliente,
    COALESCE(p.nombre, s.nombre) AS item,
    dv.tipo,
    dv.cantidad,
    dv.precio_unitario,
    dv.subtotal AS valor_item,
    v.total AS total_venta
   FROM ((((public.ventas v
     LEFT JOIN public.usuarios c ON ((c.id = v.cliente_id)))
     JOIN public.detalle_ventas dv ON ((dv.venta_id = v.id)))
     LEFT JOIN public.productos p ON ((p.id = dv.producto_id)))
     LEFT JOIN public.servicios s ON ((s.id = dv.servicio_id)));



--
-- TOC entry 260 (class 1259 OID 16992)
-- Name: vw_ventas_por_dia; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_ventas_por_dia AS
 SELECT date(fecha) AS fecha,
    count(*) AS cantidad_ventas,
    COALESCE(sum(total), (0)::numeric) AS total_vendido
   FROM public.ventas
  WHERE ((estado)::text = 'pagada'::text)
  GROUP BY (date(fecha))
  ORDER BY (date(fecha));



--
-- TOC entry 261 (class 1259 OID 16996)
-- Name: vw_ventas_por_mes; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_ventas_por_mes AS
 SELECT (date_trunc('month'::text, fecha))::date AS mes,
    count(*) AS cantidad_ventas,
    COALESCE(sum(total), (0)::numeric) AS total_vendido
   FROM public.ventas
  WHERE ((estado)::text = 'pagada'::text)
  GROUP BY (date_trunc('month'::text, fecha))
  ORDER BY (date_trunc('month'::text, fecha));



--
-- TOC entry 5371 (class 0 OID 16417)
-- Dependencies: 224
-- Data for Name: categorias; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.categorias (id, nombre, descripcion, estado, created_at, updated_at) VALUES
('1', 'Acción', 'Videojuegos enfocados en acción', 'activo', '2026-08-25 03:08:28', '2026-08-25 03:08:28'),
('2', 'Aventura', 'Videojuegos de aventura', 'activo', '2026-08-25 03:08:28', '2026-08-25 03:08:28'),
('3', 'Mundo abierto', 'Videojuegos con exploración libre', 'activo', '2026-08-25 03:08:28', '2026-08-25 03:08:28'),
('4', 'Supervivencia', 'Videojuegos de supervivencia', 'activo', '2026-08-25 03:08:28', '2026-08-25 03:08:28');

--
-- TOC entry 5401 (class 0 OID 16879)
-- Dependencies: 254
-- Data for Name: conversaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.conversaciones (id, usuario_id, pqr_id, canal, estado, titulo, created_at, updated_at) VALUES
('2', '2', NULL, 'web', 'activa', 'Asistencia GameZone', '2026-09-18 14:43:12.915216', '2026-09-18 14:43:12.915216'),
('3', '3', NULL, 'web', 'activa', 'Asistencia GameZone', '2026-09-18 14:43:30.336926', '2026-09-18 14:43:30.336926'),
('4', '8', NULL, 'web', 'activa', 'Asistencia GameZone', '2026-09-18 15:09:51.074374', '2026-09-18 15:09:51.074374'),
('5', '12', NULL, 'web', 'activa', 'Asistencia GameZone', '2026-09-22 13:04:36.82006', '2026-09-22 13:04:36.82006');

--
-- TOC entry 5393 (class 0 OID 16759)
-- Dependencies: 246
-- Data for Name: detalle_facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.detalle_facturas (id, factura_id, producto_id, servicio_id, tipo, descripcion, cantidad, precio_unitario, descuento, subtotal) VALUES
('1', '1', '2', NULL, 'producto', 'God of War', '1', '119900.00', '0.00', '119900.00'),
('2', '2', '4', NULL, 'producto', 'The Last of Us', '1', '109900.00', '0.00', '109900.00'),
('3', '3', '1', NULL, 'producto', 'Ghost of Tsushima', '1', '129900.00', '0.00', '129900.00'),
('4', '4', '1', NULL, 'producto', 'Ghost of Tsushima', '1', '129900.00', '0.00', '129900.00'),
('5', '4', '8', NULL, 'producto', 'EA SPORTS FC 27 Edición Estándar para PS4 y PS5', '1', '129900.00', '0.00', '129900.00'),
('6', '5', NULL, '3', 'servicio', 's HD', '1', '200000.00', '0.00', '200000.00');

--
-- TOC entry 5388 (class 0 OID 16677)
-- Dependencies: 241
-- Data for Name: detalle_pagos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.detalle_pagos (id, payment_id, producto_id, servicio_id, tipo, cantidad, precio_unitario) VALUES
('1', '1', '3', NULL, 'producto', '1', '89900.00'),
('2', '2', '3', NULL, 'producto', '2', '89900.00'),
('3', '3', '2', NULL, 'producto', '1', '119900.00'),
('4', '8', '3', NULL, 'producto', '1', '89900.00'),
('5', '9', '2', NULL, 'producto', '1', '119900.00'),
('6', '10', '8', NULL, 'producto', '1', '129900.00'),
('7', '11', '1', NULL, 'producto', '1', '129900.00'),
('8', '15', NULL, '2', 'servicio', '1', '10000.00'),
('9', '16', NULL, '3', 'servicio', '1', '200000.00'),
('10', '20', '1', NULL, 'producto', '1', '129900.00'),
('11', '21', NULL, '3', 'servicio', '2', '200000.00'),
('12', '22', '1', NULL, 'producto', '1', '129900.00'),
('13', '23', '1', NULL, 'producto', '1', '129900.00'),
('14', '24', '1', NULL, 'producto', '1', '129900.00'),
('15', '25', '2', NULL, 'producto', '1', '119900.00'),
('16', '26', '2', NULL, 'producto', '1', '119900.00'),
('17', '27', '1', NULL, 'producto', '1', '129900.00'),
('18', '28', '1', NULL, 'producto', '1', '129900.00'),
('19', '29', '2', NULL, 'producto', '1', '119900.00'),
('20', '30', '1', NULL, 'producto', '1', '129900.00'),
('21', '31', '1', NULL, 'producto', '1', '129900.00'),
('22', '31', '8', NULL, 'producto', '1', '129900.00'),
('23', '32', NULL, '3', 'servicio', '1', '200000.00');

--
-- TOC entry 5384 (class 0 OID 16595)
-- Dependencies: 237
-- Data for Name: detalle_ventas; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.detalle_ventas (id, venta_id, producto_id, servicio_id, tipo, cantidad, precio_unitario, descuento, subtotal, created_at) VALUES
('1', '1', '1', NULL, 'producto', '1', '129900.00', '0.00', '129900.00', '2026-09-08 00:44:45'),
('2', '2', '3', NULL, 'producto', '1', '89900.00', '0.00', '89900.00', '2026-09-11 12:58:03'),
('3', '6', '5', NULL, 'producto', '1', '129900.00', '0.00', '129900.00', '2026-09-18 16:06:58.959025'),
('4', '6', '7', NULL, 'producto', '1', '99900.00', '0.00', '99900.00', '2026-09-18 16:06:58.959025'),
('5', '6', '9', NULL, 'producto', '1', '69900.00', '0.00', '69900.00', '2026-09-18 16:06:58.959025'),
('6', '6', '8', NULL, 'producto', '1', '129900.00', '0.00', '129900.00', '2026-09-18 16:06:58.959025'),
('7', '7', '2', NULL, 'producto', '1', '119900.00', '0.00', '119900.00', '2026-09-18 16:07:05.660725'),
('8', '8', '2', NULL, 'producto', '1', '119900.00', '0.00', '119900.00', '2026-09-18 16:25:30.184941'),
('9', '9', '4', NULL, 'producto', '1', '109900.00', '0.00', '109900.00', '2026-09-18 16:26:19.748289'),
('10', '11', '1', NULL, 'producto', '1', '129900.00', '0.00', '129900.00', '2026-09-18 16:44:39.297284'),
('11', '12', '2', NULL, 'producto', '1', '119900.00', '0.00', '119900.00', '2026-09-22 12:50:28.021914'),
('12', '14', '1', NULL, 'producto', '1', '129900.00', '0.00', '129900.00', '2026-09-22 12:59:06.866667'),
('13', '15', '1', NULL, 'producto', '1', '129900.00', '0.00', '129900.00', '2026-09-22 13:03:13.349443'),
('14', '15', '8', NULL, 'producto', '1', '129900.00', '0.00', '129900.00', '2026-09-22 13:03:13.349443'),
('15', '16', NULL, '3', 'servicio', '1', '200000.00', '0.00', '200000.00', '2026-09-22 13:27:17.643213');

--
-- TOC entry 5391 (class 0 OID 16710)
-- Dependencies: 244
-- Data for Name: facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.facturas (id, venta_id, cliente_id, numero_factura, fecha, subtotal, descuento, impuestos, total, moneda, estado, cliente_nombre, cliente_documento, cliente_email, created_at, updated_at) VALUES
('1', '8', '12', 'FAC-2026-000001', '2026-09-18 16:27:22.420006', '119900.00', '0.00', '0.00', '119900.00', 'COP', 'pagada', 'el Vasito', '123456786666', 'vasitoel751@gmail.com', '2026-09-18 16:27:22.420006', '2026-09-18 16:27:22.420006'),
('2', '9', '8', 'FAC-2026-000002', '2026-09-18 16:27:42.405139', '109900.00', '0.00', '0.00', '109900.00', 'COP', 'pagada', 'Laura gomez', '12345554321', 'lau@gamezone.com', '2026-09-18 16:27:42.405139', '2026-09-18 16:27:42.405139'),
('3', '14', '12', 'FAC-2026-000003', '2026-09-22 13:01:58.850074', '129900.00', '0.00', '0.00', '129900.00', 'COP', 'pagada', 'el Vasito', '123456786666', 'vasitoel751@gmail.com', '2026-09-22 13:01:58.850074', '2026-09-22 13:01:58.850074'),
('4', '15', '12', 'FAC-2026-000004', '2026-09-22 13:03:13.349443', '259800.00', '0.00', '0.00', '259800.00', 'COP', 'pagada', 'el Vasito', '123456786666', 'vasitoel751@gmail.com', '2026-09-22 13:03:13.349443', '2026-09-22 13:03:13.349443'),
('5', '16', '12', 'FAC-2026-000005', '2026-09-22 13:27:17.643213', '200000.00', '0.00', '0.00', '200000.00', 'COP', 'pagada', 'el Vasito', '123456786666', 'vasitoel751@gmail.com', '2026-09-22 13:27:17.643213', '2026-09-22 13:27:17.643213');

--
-- TOC entry 5403 (class 0 OID 16906)
-- Dependencies: 256
-- Data for Name: mensajes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.mensajes (id, conversacion_id, remitente, usuario_id, contenido, proveedor_ia, modelo_ia, tokens_entrada, tokens_salida, created_at) VALUES
('3', '2', 'usuario', '2', 'Responde únicamente: OK', NULL, NULL, NULL, NULL, '2026-09-18 14:43:12.915216'),
('4', '2', 'asistente', NULL, 'Puedo ayudarte con productos, servicios, compras, métodos de pago y PQR. Cuéntame qué necesitas encontrar.', 'faq', NULL, NULL, NULL, '2026-09-18 14:43:12.915216'),
('5', '3', 'usuario', '3', 'Responde únicamente: OK', NULL, NULL, NULL, NULL, '2026-09-18 14:43:30.336926'),
('6', '3', 'asistente', NULL, 'Puedo ayudarte con productos, servicios, compras, métodos de pago y PQR. Cuéntame qué necesitas encontrar.', 'faq', NULL, NULL, NULL, '2026-09-18 14:43:30.336926'),
('7', '4', 'usuario', '8', 'como compro un juego', NULL, NULL, NULL, NULL, '2026-09-18 15:09:51.074374'),
('8', '4', 'asistente', NULL, 'Puedes explorar los productos disponibles en el catálogo de GameZone y abrir cada ficha para consultar precio, stock y detalles.', 'faq', NULL, NULL, NULL, '2026-09-18 15:09:51.074374'),
('9', '4', 'usuario', '8', 'que opinas de los homosexuales?', NULL, NULL, NULL, NULL, '2026-09-18 15:10:07.401317'),
('10', '4', 'asistente', NULL, 'Puedo ayudarte con productos, servicios, compras, métodos de pago y PQR. Cuéntame qué necesitas encontrar.', 'faq', NULL, NULL, NULL, '2026-09-18 15:10:07.401317'),
('11', '5', 'usuario', '12', 'como funciona el pago', NULL, NULL, NULL, NULL, '2026-09-22 13:04:36.82006'),
('12', '5', 'asistente', NULL, 'El proceso de pago depende del método que elijas (tarjeta, transferencia, etc.) y de los detalles de tu compra. Para obtener información exacta sobre cómo realizar el pago en GameZone, te recomendamos contactar a nuestro equipo de soporte o crear un PQR. ¡Gracias!', 'groq', 'openai/gpt-oss-120b', '273', '127', '2026-09-22 13:04:36.82006');

--
-- TOC entry 5386 (class 0 OID 16632)
-- Dependencies: 239
-- Data for Name: pagos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.pagos (id, usuario_id, venta_id, producto_id, cantidad, proveedor, metodo_pago, stripe_session_id, stripe_payment_intent_id, referencia_externa, monto, moneda, estado, mensaje_error, created_at, updated_at) VALUES
('1', '2', NULL, '3', '1', 'stripe', NULL, 'cs_test_a1EYu7oGJ5vYbEBl2eNq4R2adEiF6Fh390EapjQYG04swqD9WG13LqmK55', NULL, NULL, '89900.00', 'COP', 'PENDING', NULL, '2026-09-11 13:17:08', '2026-09-11 13:17:10'),
('2', '2', NULL, '3', '2', 'stripe', NULL, 'cs_test_a1J38LxgdhQNgnUCkHDIuRpoRILj6gSK1JiKog8LfutUCE1fwFgGZkPL2O', NULL, NULL, '179800.00', 'COP', 'PENDING', NULL, '2026-09-11 13:17:51', '2026-09-11 13:17:51'),
('3', '2', NULL, '2', '1', 'stripe', NULL, 'cs_test_a16sF7wZCDwlKR5Xfuv8Jndtx3GtcSYLtHF4ChWgz8KJRCQ75zcd5MQh5x', NULL, NULL, '119900.00', 'COP', 'PENDING', NULL, '2026-09-11 15:11:17', '2026-09-11 15:11:18'),
('8', '3', NULL, '3', '1', 'stripe', NULL, 'cs_test_a1o6MSagNDGne2HU3q23GxIoFmjTt19tHQBy7yCBxGLwdgeWa4xIynzdF4', NULL, NULL, '89900.00', 'cop', 'PENDING', NULL, '2026-09-18 15:17:11.759401', '2026-09-18 15:17:11.759401'),
('9', '8', NULL, '2', '1', 'stripe', NULL, 'cs_test_a1cEDQPAVRUsz6ccaE6nriHcYYPZMWEDHj7ywWVCR9xz7w3FSkhcLUbrA5', NULL, NULL, '119900.00', 'cop', 'PENDING', NULL, '2026-09-18 15:17:31.510428', '2026-09-18 15:17:31.510428'),
('10', '8', NULL, '8', '1', 'stripe', NULL, 'cs_test_a1qA5g8On8fsfWvP7dImEYz6yIeoh7h3V5wjD34BGWBhwAXLmNpkDFxvSv', NULL, NULL, '129900.00', 'cop', 'PENDING', NULL, '2026-09-18 15:17:57.496889', '2026-09-18 15:17:57.496889'),
('11', '8', NULL, '1', '1', 'stripe', NULL, 'cs_test_a1bj1mFkaOeSXmW5mY2HGDruJ2Qp5Vl0jW7jFXihjO4MQXFeliHOH2CJGQ', NULL, NULL, '129900.00', 'cop', 'PENDING', NULL, '2026-09-18 15:26:33.686415', '2026-09-18 15:26:33.686415'),
('15', '8', NULL, NULL, '1', 'stripe', NULL, 'cs_test_a11bJEPnkepGnKt0Skj5oswdlMJwFKIleKkWKJvmpQ9PaT9wWT8clzwb6y', NULL, 'servicios:2', '10000.00', 'cop', 'PENDING', NULL, '2026-09-18 15:52:39.800483', '2026-09-18 15:52:39.800483'),
('16', '8', NULL, NULL, '1', 'stripe', NULL, 'cs_test_a1AWhiIzEC24X0mjKTCcDCwdqWDI6ePQIjXaDLu7EP3tEzCdOrKntuubwO', NULL, 'servicios:3', '200000.00', 'cop', 'PENDING', NULL, '2026-09-18 15:53:10.973875', '2026-09-18 15:53:10.973875'),
('20', '2', NULL, '1', '1', 'stripe', NULL, 'cs_test_a1CxxWveeVrBsqRHEEX7R1Mlr4ZQP2Tecizb4Dbuf4dJaLSvKqjXA01x3Q', NULL, NULL, '129900.00', 'cop', 'PENDING', NULL, '2026-09-18 16:22:05.962871', '2026-09-18 16:22:05.962871'),
('21', '8', NULL, NULL, '2', 'stripe', NULL, 'cs_test_a1PcHAPNg2zVaLBOlXsFN9h8IHENtXF1NEUIEqkMhnjgDaYJvew94OpW4t', NULL, 'servicios:3', '400000.00', 'cop', 'PENDING', NULL, '2026-09-18 16:29:59.20182', '2026-09-18 16:29:59.20182'),
('22', '2', NULL, '1', '1', 'stripe', NULL, 'cs_test_a1Vkm0vtnGNwr8effJyfzhno4lPzKGWHPyUGSV2IXkx98j5eaBguGrQEBl', NULL, NULL, '129900.00', 'cop', 'PENDING', NULL, '2026-09-18 16:34:22.193869', '2026-09-18 16:34:22.193869'),
('23', '8', NULL, '1', '1', 'stripe', NULL, 'cs_test_a1BvsM2mG5nhb4R0Gn57sHwp1sTkQJz1dG0oW4J4423YITP6bSMyeX1MPQ', NULL, NULL, '129900.00', 'cop', 'PENDING', NULL, '2026-09-18 16:35:27.751766', '2026-09-18 16:35:27.751766'),
('24', '8', NULL, '1', '1', 'stripe', NULL, 'cs_test_a1nmZmXLFvlK9cIpUjyBCva9Z8rh0mWsdFNavSdJeTwPJ6Zo0pq32WKT8K', NULL, NULL, '129900.00', 'cop', 'PENDING', NULL, '2026-09-18 16:38:01.696415', '2026-09-18 16:38:01.696415'),
('25', '6', NULL, '2', '1', 'stripe', NULL, 'cs_test_a1STzdp9rKuCkONMziNAuiolV7i7KZmBq6B9rw0Z5QoOv0Pkaea3fTpOIs', NULL, NULL, '119900.00', 'cop', 'PENDING', NULL, '2026-09-18 16:38:44.851853', '2026-09-18 16:38:44.851853'),
('26', '6', NULL, '2', '1', 'stripe', NULL, 'cs_test_a1JkLe76L58RsLPepT18QDHsiZIF8t6dEvt2wQoKVVquTnDvNYsgwZ4R1g', NULL, NULL, '119900.00', 'cop', 'PENDING', NULL, '2026-09-18 16:40:09.512212', '2026-09-18 16:40:09.512212'),
('27', '8', NULL, '1', '1', 'stripe', NULL, 'cs_test_a1PTVvjKASENRAIQftErE12HAuuNxfKmCpAzqbPPARdecLTNlOYMH9Yw0p', NULL, NULL, '129900.00', 'cop', 'PENDING', NULL, '2026-09-18 16:45:26.883087', '2026-09-18 16:45:26.883087'),
('28', '8', NULL, '1', '1', 'stripe', NULL, 'cs_test_a1fESMwLIxcfWCwRmnzyq91KPL0YmKG61ewNaF83if1AjAXh0CixZI5PYc', NULL, NULL, '129900.00', 'cop', 'PENDING', NULL, '2026-09-18 16:52:37.248966', '2026-09-18 16:52:37.248966'),
('29', '8', NULL, '2', '1', 'stripe', NULL, 'cs_test_a1WLcC0WS2uTm55CBfGSsNjcRXCnTKNwTDV41Q1OzE4k9Zo1rrxv8QlMAG', NULL, NULL, '119900.00', 'cop', 'PENDING', NULL, '2026-09-18 16:54:16.837123', '2026-09-18 16:54:16.837123'),
('30', '12', '14', '1', '1', 'stripe', NULL, 'cs_test_a1G4xUuSzREMDbbkq6XDKtk9BExs00NvRCSjbOVVdbEqPXIGu4HXRYHod8', 'pi_3UIXmu1OUQ0JpNyV1j7ovent', NULL, '129900.00', 'cop', 'APPROVED', NULL, '2026-09-22 12:51:30.453043', '2026-09-22 12:59:06.866667'),
('31', '12', '15', '1', '2', 'stripe', NULL, 'cs_test_b1NoJMYD3VPziQXV4iZxTeVBuhcmAyqTGwJdDyKBPGAJ7LYA9zbqPHfRGj', 'pi_3UIXxY1OUQ0JpNyV1dxG9Qn0', NULL, '259800.00', 'cop', 'APPROVED', NULL, '2026-09-22 13:02:40.170402', '2026-09-22 13:03:13.349443'),
('32', '12', '16', NULL, '1', 'stripe', NULL, 'cs_test_a12W7UgtgtISWoV5XB6MzhMQjoOcDD3R3DKZ25DGr7cwnHwthsFQ41x4HA', 'pi_3UIYKq1OUQ0JpNyV1z0SfhdZ', 'servicios:3', '200000.00', 'cop', 'APPROVED', NULL, '2026-09-22 13:26:41.745371', '2026-09-22 13:27:17.643213');

--
-- TOC entry 5380 (class 0 OID 16533)
-- Dependencies: 233
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.password_reset_tokens (id, usuario_id, token_hash, expires_at, used_at) VALUES
('1', '3', '226b5dc728913c0dc22cd1fde685842bdd3e0522db67000a0599b335ade36bc7', '2026-09-08 05:50:55', '2026-09-08 05:37:37'),
('2', '8', '4a57fbc0e705fbc6cedf8dd61e9ce0f04ca5188d68ed70c05977f72de5ef6cb6', '2026-09-08 05:58:27', '2026-09-08 05:43:48'),
('3', '3', '09f7c302f01e0c09c0b5bda43af44b3bb8745aac6988bae97074d55b7a7eb294', '2026-09-08 17:59:27', '2026-09-08 17:44:41'),
('4', '6', '5c6a96d901980f5ac0b2b211fbf806ce7e056de2f347d76c1848015d8d3ea0a5', '2026-09-10 20:11:46', '2026-09-10 19:57:26'),
('5', '8', 'eca86434c395548b8ae741eb5e37d6ab3af7f6027897849fce7c8a884efd0c66', '2026-09-11 18:33:21', '2026-09-11 20:06:54'),
('9', '3', 'ecbfe886fef055b5cdd9c9b6e91cb348986045cbe1ffb75cc19483c22e5798f5', '2026-09-18 20:13:05.055571', '2026-09-18 19:59:49.944205'),
('10', '3', '58f5f53f78b9c75c858b6f1ef8befa37d58523bd625e5c5bca098c1fd819e5e6', '2026-09-18 20:14:49.944205', '2026-09-18 20:00:38.486662'),
('11', '3', '0f024d34ef81fcff90da323be312c44786de2cb3ec59ca5ad2acc6f052578975', '2026-09-18 20:15:38.486662', '2026-09-18 20:01:51.473151'),
('12', '3', '0fc8b652b4ee27309def78e068c472e20ae66fdde91230c4d19491e214171d55', '2026-09-18 20:16:51.473151', '2026-09-18 20:02:37.469072'),
('8', '8', '21f35ad090dff15f1a58d9f50e8b9881d9c741c593a09b74fde59bd4eef63d3f', '2026-09-11 20:21:54', '2026-09-18 20:09:00.928981'),
('13', '8', '135487a0beda1342ef4f6f9201284fbaf0dd53fe6e3a7c2f7bbb8f55b9ab4d51', '2026-09-18 20:24:00.928981', '2026-09-18 20:09:18.104562'),
('7', '6', '59093f128aed29d5a18b6718a1260e9b4542d119ab74bae58c2f9a7e188323ac', '2026-09-11 19:24:03', '2026-09-18 20:57:03.254832'),
('14', '6', '66c22d35cebf147bb64b9ba47ce8d47e79e122fff9f83033558c20be44def2ea', '2026-09-18 21:12:03.254832', '2026-09-18 20:57:13.187916'),
('6', '12', 'a87dd9c8142e7ff637be1c297d2d33effcb00fe7e81f7c65909e51085f0bf883', '2026-09-11 18:35:53', '2026-09-22 17:50:48.735093'),
('15', '12', 'f613c821fd5c246d250e0f54dd7be6c02d9d18a647cf00a7331a886e673f2434', '2026-09-22 18:05:48.735093', '2026-09-22 17:51:02.698098');

--
-- TOC entry 5369 (class 0 OID 16405)
-- Dependencies: 222
-- Data for Name: permisos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.permisos (id, nombre, descripcion, created_at) VALUES
('1', 'usuarios.ver', 'Consultar usuarios', '2026-08-25 03:08:28'),
('2', 'usuarios.crear', 'Crear usuarios', '2026-08-25 03:08:28'),
('3', 'usuarios.editar', 'Editar usuarios', '2026-08-25 03:08:28'),
('4', 'usuarios.eliminar', 'Eliminar usuarios', '2026-08-25 03:08:28'),
('5', 'productos.ver', 'Consultar productos', '2026-08-25 03:08:28'),
('6', 'productos.crear', 'Crear productos', '2026-08-25 03:08:28'),
('7', 'productos.editar', 'Editar productos', '2026-08-25 03:08:28'),
('8', 'productos.eliminar', 'Eliminar productos', '2026-08-25 03:08:28'),
('9', 'servicios.ver', 'Consultar servicios', '2026-08-25 03:08:28'),
('10', 'servicios.crear', 'Crear servicios', '2026-08-25 03:08:28'),
('11', 'servicios.editar', 'Editar servicios', '2026-08-25 03:08:28'),
('12', 'servicios.eliminar', 'Eliminar servicios', '2026-08-25 03:08:28'),
('13', 'gestionar_usuarios', 'Crear, listar, editar, cambiar estado y eliminar usuarios.', '2026-09-08 05:31:35'),
('14', 'gestionar_productos', 'Crear, listar, editar y eliminar productos.', '2026-09-08 05:31:35'),
('15', 'gestionar_servicios', 'Crear, listar, editar y eliminar servicios.', '2026-09-08 05:31:35'),
('16', 'registrar_ventas', 'Registrar ventas y descontar stock.', '2026-09-08 05:31:35'),
('17', 'ventas.ver', 'Consultar historial y detalle de ventas.', '2026-09-18 13:06:38.054391'),
('18', 'ventas.crear', 'Registrar nuevas ventas.', '2026-09-18 13:06:38.054391'),
('19', 'ventas.editar', 'Actualizar estado o información operativa de ventas.', '2026-09-18 13:06:38.054391'),
('20', 'reportes.ver', 'Consultar reportes comerciales.', '2026-09-18 13:06:38.054391'),
('21', 'reportes.exportar', 'Exportar reportes a PDF, Excel o CSV.', '2026-09-18 13:06:38.054391'),
('22', 'facturas.ver', 'Consultar facturas de venta.', '2026-09-18 13:06:38.054391'),
('23', 'facturas.generar', 'Generar facturas a partir de ventas.', '2026-09-18 13:06:38.054391'),
('24', 'facturas.anular', 'Anular facturas.', '2026-09-18 13:06:38.054391'),
('25', 'pagos.ver', 'Consultar pagos y estados.', '2026-09-18 13:06:38.054391'),
('26', 'pqr.crear', 'Registrar PQR.', '2026-09-18 13:06:38.054391'),
('27', 'pqr.ver', 'Consultar PQR.', '2026-09-18 13:06:38.054391'),
('28', 'pqr.gestionar', 'Asignar, responder y cerrar PQR.', '2026-09-18 13:06:38.054391'),
('29', 'dashboard.admin', 'Consultar indicadores administrativos.', '2026-09-18 13:06:38.054391'),
('30', 'dashboard.ventas', 'Consultar métricas y gráficos de ventas.', '2026-09-18 13:06:38.054391'),
('31', 'chatbot.usar', 'Utilizar el chatbot de atención.', '2026-09-18 13:06:38.054391'),
('32', 'conversaciones.ver', 'Consultar conversaciones del chatbot.', '2026-09-18 13:06:38.054391');

--
-- TOC entry 5397 (class 0 OID 16819)
-- Dependencies: 250
-- Data for Name: pqr; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.pqr (id, cliente_id, asignado_a, tipo, asunto, descripcion, estado, prioridad, fecha_cierre, created_at, updated_at) VALUES
('1', '12', NULL, 'queja', 'Juegos absurdamente caros, el proceso de compra es una BASURA, apartame unos cuantos JUEGOS, Pero de mi vista', 'NINGUNA', 'respondida', 'media', NULL, '2026-09-22 13:33:59.715426', '2026-09-22 13:34:24.584134');

--
-- TOC entry 5399 (class 0 OID 16853)
-- Dependencies: 252
-- Data for Name: pqr_respuestas; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.pqr_respuestas (id, pqr_id, usuario_id, mensaje, es_interna, created_at) VALUES
('1', '1', '3', 'Gracias, Nos importa una Mierda', 'f', '2026-09-22 13:34:39.351695');

--
-- TOC entry 5375 (class 0 OID 16454)
-- Dependencies: 228
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.productos (id, nombre, descripcion, precio, stock, imagen, categoria_id, estado, created_at, updated_at) VALUES
('3', 'Grand Theft Auto V', 'Explora Los Santos en uno de los mundos abiertos más reconocidos.', '89900.00', '14', 'gitiey.webp', '3', 'activo', '2026-08-25 03:08:28', '2026-09-11 17:58:03'),
('5', 'Red Dead Redemption 2', 'Explora el salvaje oeste en una aventura de mundo abierto.', '129900.00', '11', 'read.jpg', '3', 'activo', '2026-08-25 03:08:28', '2026-09-18 16:06:58.959025'),
('7', 'Cyberpunk 2077', 'Juego RPG de mundo abierto.', '99900.00', '7', '972428e5d41f41daa01f83c254219a79.jpg', '3', 'activo', '2026-08-26 18:20:13', '2026-09-18 16:06:58.959025'),
('9', 'Crash Bandicoot: La trilogía', 'Colección remasterizada de la trilogía clásica de Crash Bandicoot.', '69900.00', '99', '28977dec4d7649588b0ada98fd940bb5.webp', '1', 'activo', '2026-09-11 19:10:48', '2026-09-18 16:06:58.959025'),
('4', 'The Last of Us', 'Una historia de supervivencia en un mundo devastado.', '109900.00', '7', 'thelast.jpg', '4', 'activo', '2026-08-25 03:08:28', '2026-09-18 16:26:19.748289'),
('2', 'God of War', 'Kratos se enfrenta a dioses y criaturas en una aventura épica.', '119900.00', '7', 'Gow.jpg', '1', 'activo', '2026-08-25 03:08:28', '2026-09-22 12:50:28.021914'),
('1', 'Ghost of Tsushima', 'Aventura samurái ambientada en la isla de Tsushima.', '129900.00', '8', 'ghost.png', '2', 'activo', '2026-08-25 03:08:28', '2026-09-22 13:03:13.349443'),
('8', 'EA SPORTS FC 27 Edición Estándar para PS4 y PS5', 'Reserva EA SPORTS FC 27 Edición Estándar.', '129900.00', '18', '5329f6358e1e49c4b9ad11b128f3410c.webp', '1', 'activo', '2026-09-11 18:23:37', '2026-09-22 13:03:13.349443');

--
-- TOC entry 5395 (class 0 OID 16795)
-- Dependencies: 248
-- Data for Name: reportes_generados; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.reportes_generados (id, usuario_id, tipo, formato, fecha_inicial, fecha_final, filtros, nombre_archivo, ruta_archivo, created_at) VALUES
('2', '3', 'ventas_diarias', 'PDF', '2026-09-18', '2026-09-18', '{"fecha": "2026-09-18"}', 'reporte-ventas-2026-09-18.pdf', NULL, '2026-09-18 14:44:58.660244'),
('3', '3', 'ventas_diarias', 'XLSX', '2026-09-18', '2026-09-18', '{"fecha": "2026-09-18"}', 'reporte-ventas-2026-09-18.xlsx', NULL, '2026-09-18 14:44:58.702938'),
('4', '3', 'ventas_diarias', 'PDF', '2026-09-18', '2026-09-18', '{"fecha": "2026-09-18"}', 'reporte-ventas-2026-09-18.pdf', NULL, '2026-09-18 16:11:43.758102');

--
-- TOC entry 5378 (class 0 OID 16515)
-- Dependencies: 231
-- Data for Name: rol_permisos; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.rol_permisos (rol_id, permiso_id) VALUES
('1', '1'),
('1', '2'),
('1', '3'),
('1', '4'),
('1', '5'),
('1', '6'),
('1', '7'),
('1', '8'),
('1', '9'),
('1', '10'),
('1', '11'),
('1', '12'),
('1', '13'),
('1', '14'),
('1', '15'),
('1', '16'),
('1', '17'),
('1', '18'),
('1', '19'),
('1', '20'),
('1', '21'),
('1', '22'),
('1', '23'),
('1', '24'),
('1', '25'),
('1', '26'),
('1', '27'),
('1', '28'),
('1', '29'),
('1', '30'),
('1', '31'),
('1', '32'),
('2', '1'),
('2', '5'),
('2', '7'),
('2', '9'),
('2', '16'),
('2', '17'),
('2', '18'),
('2', '19'),
('2', '20'),
('2', '21'),
('2', '22'),
('2', '23'),
('2', '25'),
('2', '27'),
('2', '28'),
('2', '30'),
('2', '31'),
('3', '5'),
('3', '9'),
('3', '22'),
('3', '26'),
('3', '27'),
('3', '31');

--
-- TOC entry 5367 (class 0 OID 16391)
-- Dependencies: 220
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.roles (id, nombre, descripcion, created_at, updated_at) VALUES
('1', 'Administrador', 'Acceso total al sistema', '2026-08-25 03:08:28', '2026-08-25 03:08:28'),
('2', 'Empleado', 'Acceso limitado a funciones operativas', '2026-08-25 03:08:28', '2026-08-25 03:08:28'),
('3', 'Cliente', 'Acceso a funciones de cliente', '2026-08-25 03:08:28', '2026-08-25 03:08:28');

--
-- TOC entry 5373 (class 0 OID 16434)
-- Dependencies: 226
-- Data for Name: servicios; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.servicios (id, nombre, descripcion, precio, estado, created_at, updated_at) VALUES
('1', 'Soporte técnico', 'Asistencia relacionada con la plataforma GameZone.', '0.00', 'activo', '2026-08-25 03:08:28', '2026-08-25 03:08:28'),
('2', 'Instalación asistida', 'Soporte para instalación y configuración del juego.', '10000.00', 'activo', '2026-08-26 02:48:18', '2026-08-26 02:48:18'),
('3', 's HD', 'asistencia de mujer de compañía virtual para tus lamentos y disfrute de videojuegos.', '200000.00', 'activo', '2026-08-26 19:19:36', '2026-09-22 12:33:55.159924');

--
-- TOC entry 5377 (class 0 OID 16482)
-- Dependencies: 230
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.usuarios (id, nombre, apellido, tipo_documento, numero_documento, direccion, telefono, email, password, rol_id, estado, created_at, updated_at) VALUES
('2', 'Pendejo', 'Ramirez', 'CC', '102838129', 'Medellin', '3012394985', 'pendejo@gmail.com', '$2b$12$RneSd5eV2xdW7OI3ldm/YeID7r/IVh/Y4/SaGJoPVVa3zIHtzV9Su', '3', 'activo', '2026-08-25 19:30:57', '2026-08-25 19:30:57'),
('4', 'Laura', 'Durango', 'CC', '123456782333', 'crra98 #54', '1234567655', 'laura@gamezone.com', '$2b$10$lHCInDH0BrzEE8jyoGp0Gu9AnhyniI4lSaZf2CSdr5qi2NeROILk.', '2', 'activo', '2026-08-26 01:56:37', '2026-08-26 01:56:37'),
('7', 'wilsona', 'gomez', 'TI', '12304560', 'crra98 #54', '1234567432', 'hehre@gamezone.com', '$2b$12$fYc2yNJgNToNfhGK5ryGyO8CN9EyXU2wxLt7XpgDf6y/KybjUewEe', '3', 'activo', '2026-09-02 18:12:00', '2026-09-02 18:13:22'),
('9', 'Carlos', 'Ramirez', 'CC', '1032456789', 'Calle 45 # 23-18', '3004567890', 'carlos.ramirez@test.com', '$2b$12$1hJOjFhY0j8y3z2wx82rhuxwB7FSBII3v8tZXNpbVQmFNEhTWdjBG', '3', 'activo', '2026-09-10 19:23:38', '2026-09-10 19:23:38'),
('10', 'Carlos', 'Perez', 'CC', '1234567890', 'Calle 10', '3001234567', 'carlos@test.com', '$2b$12$g535cnun9QxR1n8ys4lecuaYsoxhRLQE7Zsd/A/AsrPcJSZoUTSaG', '3', 'activo', '2026-09-10 19:26:14', '2026-09-10 19:26:14'),
('11', 'Andres', 'Gomez', 'CC', '1029384756', 'Carrera 45 # 20-30', '3019876543', 'andres.gomez.req26@test.com', '$2b$12$SSLcuWBnhKWp.Ra5d8JyU.xrpG56STa.M7U9BiOAVB8mMg2bwj9ji', '3', 'activo', '2026-09-11 04:35:31', '2026-09-11 04:35:31'),
('3', 'Admin', 'Gamezone', 'CC', '012345001', 'crra98', '1234565423', 'admin@gamezone.com', '$2b$12$nB78UR2jaP19ELxqJt851OSOLvlvTNEprT.XdspB9m20/mXfsGxqi', '1', 'activo', '2026-08-26 01:52:16', '2026-09-18 15:02:37.470771'),
('8', 'Laura', 'gomez', 'CC', '12345554321', 'crra98', '1234567776', 'lau@gamezone.com', '$2b$12$bI7DuuiCYUDMMIDxz.ID3uLfp4h9FyApb0jqUirvHNMnN0NPzmt4i', '3', 'activo', '2026-09-08 04:34:13', '2026-09-18 15:09:18.105929'),
('6', 'Emmanuel', 'Gomez', 'CC', '1020304050', 'crra98 #546', '3178837890', 'emma@gamezone.com', '$2b$12$2xjnmJi8lIEKzhleKoap2OqXEbng6asrcy697TqK7uRJyMrR/Cu/K', '2', 'activo', '2026-08-26 19:56:56', '2026-09-18 15:57:13.190407'),
('12', 'el', 'Vasito', 'CE', '123456786666', 'Caracas', '3203030303', 'vasitoel751@gmail.com', '$2b$12$NeXvbm431KEbnuiY0rFqZeplTYdSum/MVD/B6/psqd2gDj2In4Uya', '3', 'activo', '2026-09-11 18:19:40', '2026-09-22 12:51:02.699977');

--
-- TOC entry 5382 (class 0 OID 16550)
-- Dependencies: 235
-- Data for Name: ventas; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.ventas (id, cliente_id, usuario_id, subtotal, descuento, impuestos, total, moneda, estado, origen, fecha, observaciones, created_at, updated_at) VALUES
('1', NULL, '6', '129900.00', '0.00', '0.00', '129900.00', 'COP', 'pagada', 'legacy', '2026-09-08 00:44:45', 'Migrada desde la estructura anterior sin cliente explícito.', '2026-09-08 00:44:45', '2026-09-08 00:44:45'),
('2', NULL, '6', '89900.00', '0.00', '0.00', '89900.00', 'COP', 'pagada', 'legacy', '2026-09-11 12:58:03', 'Migrada desde la estructura anterior sin cliente explícito.', '2026-09-11 12:58:03', '2026-09-11 12:58:03'),
('6', NULL, '6', '429600.00', '0.00', '0.00', '429600.00', 'COP', 'pagada', 'empleado', '2026-09-18 16:06:58.959025', NULL, '2026-09-18 16:06:58.959025', '2026-09-18 16:06:58.959025'),
('7', NULL, '6', '119900.00', '0.00', '0.00', '119900.00', 'COP', 'pagada', 'empleado', '2026-09-18 16:07:05.660725', NULL, '2026-09-18 16:07:05.660725', '2026-09-18 16:07:05.660725'),
('8', '12', '6', '119900.00', '0.00', '0.00', '119900.00', 'COP', 'pagada', 'empleado', '2026-09-18 16:25:30.184941', NULL, '2026-09-18 16:25:30.184941', '2026-09-18 16:25:30.184941'),
('9', '8', '6', '109900.00', '0.00', '0.00', '109900.00', 'COP', 'pagada', 'empleado', '2026-09-18 16:26:19.748289', NULL, '2026-09-18 16:26:19.748289', '2026-09-18 16:26:19.748289'),
('11', '2', '6', '129900.00', '0.00', '0.00', '129900.00', 'COP', 'pagada', 'empleado', '2026-09-18 16:44:39.297284', NULL, '2026-09-18 16:44:39.297284', '2026-09-18 16:44:39.297284'),
('12', '12', '6', '119900.00', '0.00', '0.00', '119900.00', 'COP', 'pagada', 'empleado', '2026-09-22 12:50:28.021914', NULL, '2026-09-22 12:50:28.021914', '2026-09-22 12:50:28.021914'),
('14', '12', '12', '129900.00', '0.00', '0.00', '129900.00', 'COP', 'pagada', 'web', '2026-09-22 12:59:06.866667', NULL, '2026-09-22 12:59:06.866667', '2026-09-22 12:59:06.866667'),
('15', '12', '12', '259800.00', '0.00', '0.00', '259800.00', 'COP', 'pagada', 'web', '2026-09-22 13:03:13.349443', NULL, '2026-09-22 13:03:13.349443', '2026-09-22 13:03:13.349443'),
('16', '12', '12', '200000.00', '0.00', '0.00', '200000.00', 'COP', 'pagada', 'web', '2026-09-22 13:27:17.643213', NULL, '2026-09-22 13:27:17.643213', '2026-09-22 13:27:17.643213');

--
-- TOC entry 5409 (class 0 OID 0)
-- Dependencies: 223
-- Name: categorias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categorias_id_seq', 4, true);


--
-- TOC entry 5410 (class 0 OID 0)
-- Dependencies: 253
-- Name: conversaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.conversaciones_id_seq', 5, true);


--
-- TOC entry 5411 (class 0 OID 0)
-- Dependencies: 245
-- Name: detalle_facturas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_facturas_id_seq', 6, true);


--
-- TOC entry 5412 (class 0 OID 0)
-- Dependencies: 240
-- Name: detalle_pagos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_pagos_id_seq', 23, true);


--
-- TOC entry 5413 (class 0 OID 0)
-- Dependencies: 236
-- Name: detalle_ventas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_ventas_id_seq', 15, true);


--
-- TOC entry 5414 (class 0 OID 0)
-- Dependencies: 242
-- Name: factura_numero_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.factura_numero_seq', 5, true);


--
-- TOC entry 5415 (class 0 OID 0)
-- Dependencies: 243
-- Name: facturas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.facturas_id_seq', 5, true);


--
-- TOC entry 5416 (class 0 OID 0)
-- Dependencies: 255
-- Name: mensajes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mensajes_id_seq', 12, true);


--
-- TOC entry 5417 (class 0 OID 0)
-- Dependencies: 238
-- Name: pagos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pagos_id_seq', 32, true);


--
-- TOC entry 5418 (class 0 OID 0)
-- Dependencies: 232
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_reset_tokens_id_seq', 15, true);


--
-- TOC entry 5419 (class 0 OID 0)
-- Dependencies: 221
-- Name: permisos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permisos_id_seq', 36, true);


--
-- TOC entry 5420 (class 0 OID 0)
-- Dependencies: 249
-- Name: pqr_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pqr_id_seq', 1, true);


--
-- TOC entry 5421 (class 0 OID 0)
-- Dependencies: 251
-- Name: pqr_respuestas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pqr_respuestas_id_seq', 1, true);


--
-- TOC entry 5422 (class 0 OID 0)
-- Dependencies: 227
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.productos_id_seq', 11, true);


--
-- TOC entry 5423 (class 0 OID 0)
-- Dependencies: 247
-- Name: reportes_generados_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reportes_generados_id_seq', 4, true);


--
-- TOC entry 5424 (class 0 OID 0)
-- Dependencies: 219
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 6, true);


--
-- TOC entry 5425 (class 0 OID 0)
-- Dependencies: 225
-- Name: servicios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.servicios_id_seq', 3, true);


--
-- TOC entry 5426 (class 0 OID 0)
-- Dependencies: 229
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 12, true);


--
-- TOC entry 5427 (class 0 OID 0)
-- Dependencies: 234
-- Name: ventas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ventas_id_seq', 16, true);


--
-- TOC entry 5089 (class 2606 OID 16432)
-- Name: categorias categorias_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_nombre_key UNIQUE (nombre);


--
-- TOC entry 5091 (class 2606 OID 16430)
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- TOC entry 5166 (class 2606 OID 16894)
-- Name: conversaciones conversaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT conversaciones_pkey PRIMARY KEY (id);


--
-- TOC entry 5150 (class 2606 OID 16778)
-- Name: detalle_facturas detalle_facturas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_facturas
    ADD CONSTRAINT detalle_facturas_pkey PRIMARY KEY (id);


--
-- TOC entry 5136 (class 2606 OID 16691)
-- Name: detalle_pagos detalle_pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_pagos
    ADD CONSTRAINT detalle_pagos_pkey PRIMARY KEY (id);


--
-- TOC entry 5120 (class 2606 OID 16615)
-- Name: detalle_ventas detalle_ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_ventas
    ADD CONSTRAINT detalle_ventas_pkey PRIMARY KEY (id);


--
-- TOC entry 5141 (class 2606 OID 16747)
-- Name: facturas facturas_numero_factura_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT facturas_numero_factura_key UNIQUE (numero_factura);


--
-- TOC entry 5143 (class 2606 OID 16743)
-- Name: facturas facturas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT facturas_pkey PRIMARY KEY (id);


--
-- TOC entry 5145 (class 2606 OID 16745)
-- Name: facturas facturas_venta_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT facturas_venta_id_key UNIQUE (venta_id);


--
-- TOC entry 5172 (class 2606 OID 16921)
-- Name: mensajes mensajes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT mensajes_pkey PRIMARY KEY (id);


--
-- TOC entry 5130 (class 2606 OID 16656)
-- Name: pagos pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_pkey PRIMARY KEY (id);


--
-- TOC entry 5132 (class 2606 OID 16660)
-- Name: pagos pagos_stripe_payment_intent_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_stripe_payment_intent_id_key UNIQUE (stripe_payment_intent_id);


--
-- TOC entry 5134 (class 2606 OID 16658)
-- Name: pagos pagos_stripe_session_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_stripe_session_id_key UNIQUE (stripe_session_id);


--
-- TOC entry 5109 (class 2606 OID 16541)
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 5111 (class 2606 OID 16543)
-- Name: password_reset_tokens password_reset_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_hash_key UNIQUE (token_hash);


--
-- TOC entry 5085 (class 2606 OID 16415)
-- Name: permisos permisos_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_nombre_key UNIQUE (nombre);


--
-- TOC entry 5087 (class 2606 OID 16413)
-- Name: permisos permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_pkey PRIMARY KEY (id);


--
-- TOC entry 5161 (class 2606 OID 16841)
-- Name: pqr pqr_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pqr
    ADD CONSTRAINT pqr_pkey PRIMARY KEY (id);


--
-- TOC entry 5164 (class 2606 OID 16867)
-- Name: pqr_respuestas pqr_respuestas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pqr_respuestas
    ADD CONSTRAINT pqr_respuestas_pkey PRIMARY KEY (id);


--
-- TOC entry 5096 (class 2606 OID 16475)
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- TOC entry 5155 (class 2606 OID 16812)
-- Name: reportes_generados reportes_generados_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reportes_generados
    ADD CONSTRAINT reportes_generados_pkey PRIMARY KEY (id);


--
-- TOC entry 5106 (class 2606 OID 16521)
-- Name: rol_permisos rol_permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permisos
    ADD CONSTRAINT rol_permisos_pkey PRIMARY KEY (rol_id, permiso_id);


--
-- TOC entry 5081 (class 2606 OID 16403)
-- Name: roles roles_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_nombre_key UNIQUE (nombre);


--
-- TOC entry 5083 (class 2606 OID 16401)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 5093 (class 2606 OID 16452)
-- Name: servicios servicios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.servicios
    ADD CONSTRAINT servicios_pkey PRIMARY KEY (id);


--
-- TOC entry 5099 (class 2606 OID 16509)
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- TOC entry 5101 (class 2606 OID 16507)
-- Name: usuarios usuarios_numero_documento_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_numero_documento_key UNIQUE (numero_documento);


--
-- TOC entry 5103 (class 2606 OID 16505)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 5118 (class 2606 OID 16583)
-- Name: ventas ventas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT ventas_pkey PRIMARY KEY (id);


--
-- TOC entry 5167 (class 1259 OID 16964)
-- Name: ix_conversaciones_pqr; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_conversaciones_pqr ON public.conversaciones USING btree (pqr_id);


--
-- TOC entry 5168 (class 1259 OID 16963)
-- Name: ix_conversaciones_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_conversaciones_usuario ON public.conversaciones USING btree (usuario_id);


--
-- TOC entry 5151 (class 1259 OID 16955)
-- Name: ix_detalle_facturas_factura; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_detalle_facturas_factura ON public.detalle_facturas USING btree (factura_id);


--
-- TOC entry 5137 (class 1259 OID 16949)
-- Name: ix_detalle_pagos_pago; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_detalle_pagos_pago ON public.detalle_pagos USING btree (payment_id);


--
-- TOC entry 5138 (class 1259 OID 16950)
-- Name: ix_detalle_pagos_producto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_detalle_pagos_producto ON public.detalle_pagos USING btree (producto_id);


--
-- TOC entry 5139 (class 1259 OID 16951)
-- Name: ix_detalle_pagos_servicio; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_detalle_pagos_servicio ON public.detalle_pagos USING btree (servicio_id);


--
-- TOC entry 5121 (class 1259 OID 16942)
-- Name: ix_detalle_ventas_producto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_detalle_ventas_producto ON public.detalle_ventas USING btree (producto_id);


--
-- TOC entry 5122 (class 1259 OID 16943)
-- Name: ix_detalle_ventas_servicio; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_detalle_ventas_servicio ON public.detalle_ventas USING btree (servicio_id);


--
-- TOC entry 5123 (class 1259 OID 16941)
-- Name: ix_detalle_ventas_venta; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_detalle_ventas_venta ON public.detalle_ventas USING btree (venta_id);


--
-- TOC entry 5146 (class 1259 OID 16952)
-- Name: ix_facturas_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_facturas_cliente ON public.facturas USING btree (cliente_id);


--
-- TOC entry 5147 (class 1259 OID 16954)
-- Name: ix_facturas_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_facturas_estado ON public.facturas USING btree (estado);


--
-- TOC entry 5148 (class 1259 OID 16953)
-- Name: ix_facturas_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_facturas_fecha ON public.facturas USING btree (fecha);


--
-- TOC entry 5169 (class 1259 OID 16965)
-- Name: ix_mensajes_conversacion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_mensajes_conversacion ON public.mensajes USING btree (conversacion_id);


--
-- TOC entry 5170 (class 1259 OID 16966)
-- Name: ix_mensajes_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_mensajes_created_at ON public.mensajes USING btree (created_at);


--
-- TOC entry 5124 (class 1259 OID 16948)
-- Name: ix_pagos_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pagos_created_at ON public.pagos USING btree (created_at);


--
-- TOC entry 5125 (class 1259 OID 16947)
-- Name: ix_pagos_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pagos_estado ON public.pagos USING btree (estado);


--
-- TOC entry 5126 (class 1259 OID 16946)
-- Name: ix_pagos_producto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pagos_producto ON public.pagos USING btree (producto_id);


--
-- TOC entry 5127 (class 1259 OID 16944)
-- Name: ix_pagos_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pagos_usuario ON public.pagos USING btree (usuario_id);


--
-- TOC entry 5128 (class 1259 OID 16945)
-- Name: ix_pagos_venta; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pagos_venta ON public.pagos USING btree (venta_id);


--
-- TOC entry 5107 (class 1259 OID 16935)
-- Name: ix_password_reset_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_password_reset_usuario ON public.password_reset_tokens USING btree (usuario_id);


--
-- TOC entry 5156 (class 1259 OID 16959)
-- Name: ix_pqr_asignado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pqr_asignado ON public.pqr USING btree (asignado_a);


--
-- TOC entry 5157 (class 1259 OID 16958)
-- Name: ix_pqr_cliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pqr_cliente ON public.pqr USING btree (cliente_id);


--
-- TOC entry 5158 (class 1259 OID 16961)
-- Name: ix_pqr_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pqr_created_at ON public.pqr USING btree (created_at);


--
-- TOC entry 5159 (class 1259 OID 16960)
-- Name: ix_pqr_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pqr_estado ON public.pqr USING btree (estado);


--
-- TOC entry 5162 (class 1259 OID 16962)
-- Name: ix_pqr_respuestas_pqr; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_pqr_respuestas_pqr ON public.pqr_respuestas USING btree (pqr_id);


--
-- TOC entry 5094 (class 1259 OID 16932)
-- Name: ix_productos_categoria_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_productos_categoria_id ON public.productos USING btree (categoria_id);


--
-- TOC entry 5152 (class 1259 OID 16956)
-- Name: ix_reportes_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_reportes_fecha ON public.reportes_generados USING btree (created_at);


--
-- TOC entry 5153 (class 1259 OID 16957)
-- Name: ix_reportes_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_reportes_usuario ON public.reportes_generados USING btree (usuario_id);


--
-- TOC entry 5104 (class 1259 OID 16934)
-- Name: ix_rol_permisos_permiso_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_rol_permisos_permiso_id ON public.rol_permisos USING btree (permiso_id);


--
-- TOC entry 5097 (class 1259 OID 16933)
-- Name: ix_usuarios_rol_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_usuarios_rol_id ON public.usuarios USING btree (rol_id);


--
-- TOC entry 5112 (class 1259 OID 16936)
-- Name: ix_ventas_cliente_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_ventas_cliente_id ON public.ventas USING btree (cliente_id);


--
-- TOC entry 5113 (class 1259 OID 16939)
-- Name: ix_ventas_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_ventas_estado ON public.ventas USING btree (estado);


--
-- TOC entry 5114 (class 1259 OID 16938)
-- Name: ix_ventas_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_ventas_fecha ON public.ventas USING btree (fecha);


--
-- TOC entry 5115 (class 1259 OID 16940)
-- Name: ix_ventas_total; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_ventas_total ON public.ventas USING btree (total);


--
-- TOC entry 5116 (class 1259 OID 16937)
-- Name: ix_ventas_usuario_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_ventas_usuario_id ON public.ventas USING btree (usuario_id);


--
-- TOC entry 5204 (class 2620 OID 16968)
-- Name: categorias trg_categorias_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_categorias_updated_at BEFORE UPDATE ON public.categorias FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5212 (class 2620 OID 16976)
-- Name: conversaciones trg_conversaciones_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_conversaciones_updated_at BEFORE UPDATE ON public.conversaciones FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5210 (class 2620 OID 16974)
-- Name: facturas trg_facturas_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_facturas_updated_at BEFORE UPDATE ON public.facturas FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5209 (class 2620 OID 16973)
-- Name: pagos trg_pagos_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_pagos_updated_at BEFORE UPDATE ON public.pagos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5211 (class 2620 OID 16975)
-- Name: pqr trg_pqr_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_pqr_updated_at BEFORE UPDATE ON public.pqr FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5206 (class 2620 OID 16970)
-- Name: productos trg_productos_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_productos_updated_at BEFORE UPDATE ON public.productos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5203 (class 2620 OID 16967)
-- Name: roles trg_roles_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_roles_updated_at BEFORE UPDATE ON public.roles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5205 (class 2620 OID 16969)
-- Name: servicios trg_servicios_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_servicios_updated_at BEFORE UPDATE ON public.servicios FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5207 (class 2620 OID 16971)
-- Name: usuarios trg_usuarios_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_usuarios_updated_at BEFORE UPDATE ON public.usuarios FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5208 (class 2620 OID 16972)
-- Name: ventas trg_ventas_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_ventas_updated_at BEFORE UPDATE ON public.ventas FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5199 (class 2606 OID 16900)
-- Name: conversaciones fk_conversaciones_pqr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT fk_conversaciones_pqr FOREIGN KEY (pqr_id) REFERENCES public.pqr(id) ON DELETE SET NULL;


--
-- TOC entry 5200 (class 2606 OID 16895)
-- Name: conversaciones fk_conversaciones_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversaciones
    ADD CONSTRAINT fk_conversaciones_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;


--
-- TOC entry 5191 (class 2606 OID 16779)
-- Name: detalle_facturas fk_detalle_facturas_factura; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_facturas
    ADD CONSTRAINT fk_detalle_facturas_factura FOREIGN KEY (factura_id) REFERENCES public.facturas(id) ON DELETE CASCADE;


--
-- TOC entry 5192 (class 2606 OID 16784)
-- Name: detalle_facturas fk_detalle_facturas_producto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_facturas
    ADD CONSTRAINT fk_detalle_facturas_producto FOREIGN KEY (producto_id) REFERENCES public.productos(id) ON DELETE SET NULL;


--
-- TOC entry 5193 (class 2606 OID 16789)
-- Name: detalle_facturas fk_detalle_facturas_servicio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_facturas
    ADD CONSTRAINT fk_detalle_facturas_servicio FOREIGN KEY (servicio_id) REFERENCES public.servicios(id) ON DELETE SET NULL;


--
-- TOC entry 5186 (class 2606 OID 16692)
-- Name: detalle_pagos fk_detalle_pagos_pago; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_pagos
    ADD CONSTRAINT fk_detalle_pagos_pago FOREIGN KEY (payment_id) REFERENCES public.pagos(id) ON DELETE CASCADE;


--
-- TOC entry 5187 (class 2606 OID 16697)
-- Name: detalle_pagos fk_detalle_pagos_producto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_pagos
    ADD CONSTRAINT fk_detalle_pagos_producto FOREIGN KEY (producto_id) REFERENCES public.productos(id) ON DELETE RESTRICT;


--
-- TOC entry 5188 (class 2606 OID 16702)
-- Name: detalle_pagos fk_detalle_pagos_servicio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_pagos
    ADD CONSTRAINT fk_detalle_pagos_servicio FOREIGN KEY (servicio_id) REFERENCES public.servicios(id) ON DELETE RESTRICT;


--
-- TOC entry 5180 (class 2606 OID 16621)
-- Name: detalle_ventas fk_detalle_ventas_producto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_ventas
    ADD CONSTRAINT fk_detalle_ventas_producto FOREIGN KEY (producto_id) REFERENCES public.productos(id) ON DELETE RESTRICT;


--
-- TOC entry 5181 (class 2606 OID 16626)
-- Name: detalle_ventas fk_detalle_ventas_servicio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_ventas
    ADD CONSTRAINT fk_detalle_ventas_servicio FOREIGN KEY (servicio_id) REFERENCES public.servicios(id) ON DELETE RESTRICT;


--
-- TOC entry 5182 (class 2606 OID 16616)
-- Name: detalle_ventas fk_detalle_ventas_venta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_ventas
    ADD CONSTRAINT fk_detalle_ventas_venta FOREIGN KEY (venta_id) REFERENCES public.ventas(id) ON DELETE CASCADE;


--
-- TOC entry 5189 (class 2606 OID 16753)
-- Name: facturas fk_facturas_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT fk_facturas_cliente FOREIGN KEY (cliente_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- TOC entry 5190 (class 2606 OID 16748)
-- Name: facturas fk_facturas_venta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT fk_facturas_venta FOREIGN KEY (venta_id) REFERENCES public.ventas(id) ON DELETE RESTRICT;


--
-- TOC entry 5201 (class 2606 OID 16922)
-- Name: mensajes fk_mensajes_conversacion; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT fk_mensajes_conversacion FOREIGN KEY (conversacion_id) REFERENCES public.conversaciones(id) ON DELETE CASCADE;


--
-- TOC entry 5202 (class 2606 OID 16927)
-- Name: mensajes fk_mensajes_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensajes
    ADD CONSTRAINT fk_mensajes_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;


--
-- TOC entry 5183 (class 2606 OID 16671)
-- Name: pagos fk_pagos_producto; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT fk_pagos_producto FOREIGN KEY (producto_id) REFERENCES public.productos(id) ON DELETE SET NULL;


--
-- TOC entry 5184 (class 2606 OID 16661)
-- Name: pagos fk_pagos_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT fk_pagos_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- TOC entry 5185 (class 2606 OID 16666)
-- Name: pagos fk_pagos_venta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT fk_pagos_venta FOREIGN KEY (venta_id) REFERENCES public.ventas(id) ON DELETE SET NULL;


--
-- TOC entry 5177 (class 2606 OID 16544)
-- Name: password_reset_tokens fk_password_reset_tokens_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fk_password_reset_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- TOC entry 5195 (class 2606 OID 16847)
-- Name: pqr fk_pqr_asignado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pqr
    ADD CONSTRAINT fk_pqr_asignado FOREIGN KEY (asignado_a) REFERENCES public.usuarios(id) ON DELETE SET NULL;


--
-- TOC entry 5196 (class 2606 OID 16842)
-- Name: pqr fk_pqr_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pqr
    ADD CONSTRAINT fk_pqr_cliente FOREIGN KEY (cliente_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- TOC entry 5197 (class 2606 OID 16868)
-- Name: pqr_respuestas fk_pqr_respuestas_pqr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pqr_respuestas
    ADD CONSTRAINT fk_pqr_respuestas_pqr FOREIGN KEY (pqr_id) REFERENCES public.pqr(id) ON DELETE CASCADE;


--
-- TOC entry 5198 (class 2606 OID 16873)
-- Name: pqr_respuestas fk_pqr_respuestas_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pqr_respuestas
    ADD CONSTRAINT fk_pqr_respuestas_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- TOC entry 5173 (class 2606 OID 16476)
-- Name: productos fk_productos_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT fk_productos_categoria FOREIGN KEY (categoria_id) REFERENCES public.categorias(id) ON DELETE SET NULL;


--
-- TOC entry 5194 (class 2606 OID 16813)
-- Name: reportes_generados fk_reportes_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reportes_generados
    ADD CONSTRAINT fk_reportes_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- TOC entry 5175 (class 2606 OID 16527)
-- Name: rol_permisos fk_rol_permisos_permiso; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permisos
    ADD CONSTRAINT fk_rol_permisos_permiso FOREIGN KEY (permiso_id) REFERENCES public.permisos(id) ON DELETE CASCADE;


--
-- TOC entry 5176 (class 2606 OID 16522)
-- Name: rol_permisos fk_rol_permisos_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permisos
    ADD CONSTRAINT fk_rol_permisos_rol FOREIGN KEY (rol_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- TOC entry 5174 (class 2606 OID 16510)
-- Name: usuarios fk_usuarios_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk_usuarios_rol FOREIGN KEY (rol_id) REFERENCES public.roles(id);


--
-- TOC entry 5178 (class 2606 OID 16584)
-- Name: ventas fk_ventas_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fk_ventas_cliente FOREIGN KEY (cliente_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT;


--
-- TOC entry 5179 (class 2606 OID 16589)
-- Name: ventas fk_ventas_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ventas
    ADD CONSTRAINT fk_ventas_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE SET NULL;


-- Completed on 2026-09-22 16:49:53

--
-- PostgreSQL database dump complete
--

COMMIT;
